class Color{
	constructor() {
		var r,g,b;
		if(arguments.length === 1) {
			var hexa = arguments[0].toLowerCase();
			if(hexa.match(/^#[0-9a-f]{6}$/i)) {
				hexa = /^#?([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i.exec(hexa);
				if(hexa && hexa.length === 4) {
					r = parseInt(hexa[1], 16);
					g = parseInt(hexa[2], 16);
					b = parseInt(hexa[3], 16);
				}
			}
		} else if(arguments.length === 3) {
			r = arguments[0];
			g = arguments[1];
			b = arguments[2];
		}
		this.r = ~~r || 0;
		this.g = ~~g || 0;
		this.b = ~~b || 0;
	}

	distance(color) {
		var d = 0;
		d += Math.pow(this.r - color.r, 2);
		d += Math.pow(this.g - color.g, 2);
		d += Math.pow(this.b - color.b, 2);
		return Math.abs(Math.sqrt(d));
	}

	add(r, g, b) {
		this.r += r;
		this.g += g;
		this.b += b;
		if(this.r < 0) this.r = 0;
		else if(this.r > 255) this.r = 255;
		if(this.g < 0) this.g = 0;
		else if(this.g > 255) this.g = 255;
		if(this.b < 0) this.b = 0;
		else if(this.b > 255) this.b = 255;
	}

	toHexa() {
		var r = (~~this.r || 0).toString(16), g = (~~this.g || 0).toString(16), b = (~~this.b || 0).toString(16);
		if(r.length == 1) r = "0" + r;
		if(g.length == 1) g = "0" + g;
		if(b.length == 1) b = "0" + b;
		return "#"+r+g+b;
	}

	getName() {
		var hexa = this.toHexa();
		var low = 256;
		var name;
		for(var n in Color.map) {
			if(!Color.map.hasOwnProperty(n))
				continue;
			var color = Color.map[n];
			if(color.r === this.r && color.g === this.g && color.b === this.b) {
				return n;
			}
			var dist = this.distance(color);
			if(dist < low) {
				low = dist;
				name = n;
			}
		}
		if(!name)
			name = this.toHexa();
		else
			name = "A shade of " + name;
		return name;
	}

	static map = {};

	static addToMap(hexa, name) {
		this.map[name] = new this(hexa);
	}

	static {
		this.addToMap("#7CB9E8", "Aero");
		this.addToMap("#C9FFE5", "Aero blue");
		this.addToMap("#B284BE", "African purple");
		this.addToMap("#5D8AA8", "Air Force blue (RAF)");
		this.addToMap("#00308F", "Air Force blue (USAF)");
		this.addToMap("#72A0C1", "Air superiority blue");
		this.addToMap("#AF002A", "Alabama Crimson");
		this.addToMap("#F0F8FF", "Alice blue");
		this.addToMap("#E32636", "Alizarin crimson");
		this.addToMap("#C46210", "Alloy orange");
		this.addToMap("#EFDECD", "Almond");
		this.addToMap("#E52B50", "Amaranth");
		this.addToMap("#F19CBB", "Amaranth pink");
		this.addToMap("#AB274F", "Dark amaranth");
		this.addToMap("#3B7A57", "Amazon");
		this.addToMap("#FF7E00", "Amber");
		this.addToMap("#FF033E", "American rose");
		this.addToMap("#9966CC", "Amethyst");
		this.addToMap("#A4C639", "Android green");
		this.addToMap("#F2F3F4", "Anti-flash white");
		this.addToMap("#CD9575", "Antique brass");
		this.addToMap("#665D1E", "Antique bronze");
		this.addToMap("#915C83", "Antique fuchsia");
		this.addToMap("#841B2D", "Antique ruby");
		this.addToMap("#FAEBD7", "Antique white");
		this.addToMap("#8DB600", "Apple green");
		this.addToMap("#FBCEB1", "Apricot");
		this.addToMap("#00FFFF", "Aqua");
		this.addToMap("#7FFFD4", "Aquamarine");
		this.addToMap("#4B5320", "Army green");
		this.addToMap("#3B444B", "Arsenic");
		this.addToMap("#8F9779", "Artichoke");
		this.addToMap("#B2BEB5", "Ash grey");
		this.addToMap("#87A96B", "Asparagus");
		this.addToMap("#FDEE00", "Aureolin");
		this.addToMap("#6E7F80", "AuroMetalSaurus");
		this.addToMap("#568203", "Avocado");
		this.addToMap("#007FFF", "Azure");
		this.addToMap("#F0FFFF", "Azure mist/web");
		this.addToMap("#89CFF0", "Baby blue");
		this.addToMap("#A1CAF1", "Baby blue eyes");
		this.addToMap("#FEFEFA", "Baby powder");
		this.addToMap("#FF91AF", "Baker-Miller pink");
		this.addToMap("#21ABCD", "Ball blue");
		this.addToMap("#FAE7B5", "Banana Mania");
		this.addToMap("#FFE135", "Banana yellow");
		this.addToMap("#E0218A", "Barbie pink");
		this.addToMap("#7C0A02", "Barn red");
		this.addToMap("#848482", "Battleship grey");
		this.addToMap("#98777B", "Bazaar");
		this.addToMap("#9F8170", "Beaver");
		this.addToMap("#F5F5DC", "Beige");
		this.addToMap("#2E5894", "B'dazzled blue");
		this.addToMap("#9C2542", "Big dip o’ruby");
		this.addToMap("#FFE4C4", "Bisque");
		this.addToMap("#3D2B1F", "Bistre");
		this.addToMap("#967117", "Bistre brown");
		this.addToMap("#CAE00D", "Bitter lemon");
		this.addToMap("#648C11", "Bitter lime");
		this.addToMap("#FE6F5E", "Bittersweet");
		this.addToMap("#BF4F51", "Bittersweet shimmer");
		this.addToMap("#000000", "Black");
		this.addToMap("#3D0C02", "Black bean");
		this.addToMap("#253529", "Black leather jacket");
		this.addToMap("#3B3C36", "Black olive");
		this.addToMap("#FFEBCD", "Blanched almond");
		this.addToMap("#A57164", "Blast-off bronze");
		this.addToMap("#318CE7", "Bleu de France");
		this.addToMap("#ACE5EE", "Blizzard Blue");
		this.addToMap("#FAF0BE", "Blond");
		this.addToMap("#0000FF", "Blue");
		this.addToMap("#1F75FE", "Blue (Crayola)");
		this.addToMap("#0093AF", "Blue (Munsell)");
		this.addToMap("#0087BD", "Blue (NCS)");
		this.addToMap("#333399", "Blue (pigment)");
		this.addToMap("#0247FE", "Blue (RYB)");
		this.addToMap("#A2A2D0", "Blue Bell");
		this.addToMap("#6699CC", "Blue-gray");
		this.addToMap("#0D98BA", "Blue-green");
		this.addToMap("#126180", "Blue sapphire");
		this.addToMap("#8A2BE2", "Blue-violet");
		this.addToMap("#5072A7", "Blue yonder");
		this.addToMap("#4F86F7", "Blueberry");
		this.addToMap("#1C1CF0", "Bluebonnet");
		this.addToMap("#DE5D83", "Blush");
		this.addToMap("#79443B", "Bole Brown");
		this.addToMap("#0095B6", "Bondi blue");
		this.addToMap("#E3DAC9", "Bone");
		this.addToMap("#CC0000", "Boston University Red");
		this.addToMap("#006A4E", "Bottle green");
		this.addToMap("#873260", "Boysenberry");
		this.addToMap("#0070FF", "Brandeis blue");
		this.addToMap("#B5A642", "Brass");
		this.addToMap("#CB4154", "Brick red");
		this.addToMap("#1DACD6", "Bright cerulean");
		this.addToMap("#66FF00", "Bright green");
		this.addToMap("#BF94E4", "Bright lavender");
		this.addToMap("#D891EF", "Bright lilac");
		this.addToMap("#C32148", "Bright maroon");
		this.addToMap("#1974D2", "Bright navy blue");
		this.addToMap("#FF007F", "Bright pink");
		this.addToMap("#08E8DE", "Bright turquoise");
		this.addToMap("#D19FE8", "Bright ube");
		this.addToMap("#F4BBFF", "Brilliant lavender");
		this.addToMap("#FF55A3", "Brilliant rose");
		this.addToMap("#FB607F", "Brink pink");
		this.addToMap("#004225", "British racing green");
		this.addToMap("#CD7F32", "Bronze");
		this.addToMap("#737000", "Bronze Yellow");
		this.addToMap("#964B00", "Brown");
		this.addToMap("#6B4423", "Brown-nose");
		this.addToMap("#FFC1CC", "Bubble gum");
		this.addToMap("#E7FEFF", "Bubbles");
		this.addToMap("#F0DC82", "Buff");
		this.addToMap("#7BB661", "Bud green");
		this.addToMap("#480607", "Bulgarian rose");
		this.addToMap("#800020", "Burgundy");
		this.addToMap("#DEB887", "Burlywood");
		this.addToMap("#CC5500", "Burnt orange");
		this.addToMap("#8A3324", "Burnt umber");
		this.addToMap("#BD33A4", "Byzantine");
		this.addToMap("#702963", "Byzantium");
		this.addToMap("#536872", "Cadet");
		this.addToMap("#5F9EA0", "Cadet blue");
		this.addToMap("#91A3B0", "Cadet grey");
		this.addToMap("#006B3C", "Cadmium green");
		this.addToMap("#ED872D", "Cadmium orange");
		this.addToMap("#E30022", "Cadmium red");
		this.addToMap("#FFF600", "Cadmium yellow");
		this.addToMap("#A67B5B", "Cafe au lait");
		this.addToMap("#4B3621", "Cafe noir");
		this.addToMap("#1E4D2B", "Cal Poly green");
		this.addToMap("#A3C1AD", "Cambridge Blue");
		this.addToMap("#EFBBCC", "Cameo pink");
		this.addToMap("#78866B", "Camouflage green");
		this.addToMap("#FFEF00", "Canary yellow");
		this.addToMap("#FF0800", "Candy apple red");
		this.addToMap("#E4717A", "Candy pink");
		this.addToMap("#592720", "Caput mortuum");
		this.addToMap("#C41E3A", "Cardinal");
		this.addToMap("#00CC99", "Caribbean green");
		this.addToMap("#960018", "Carmine");
		this.addToMap("#EB4C42", "Carmine pink");
		this.addToMap("#FF0038", "Carmine red");
		this.addToMap("#FFA6C9", "Carnation pink");
		this.addToMap("#99BADD", "Carolina blue");
		this.addToMap("#ED9121", "Carrot orange");
		this.addToMap("#00563F", "Castleton green");
		this.addToMap("#062A78", "Catalina blue");
		this.addToMap("#703642", "Catawba");
		this.addToMap("#C95A49", "Cedar Chest");
		this.addToMap("#92A1CF", "Ceil");
		this.addToMap("#ACE1AF", "Celadon");
		this.addToMap("#007BA7", "Celadon blue");
		this.addToMap("#2F847C", "Celadon green");
		this.addToMap("#4997D0", "Celestial blue");
		this.addToMap("#EC3B83", "Cerise pink");
		this.addToMap("#2A52BE", "Cerulean blue");
		this.addToMap("#6D9BC3", "Cerulean frost");
		this.addToMap("#007AA5", "CG Blue");
		this.addToMap("#E03C31", "CG Red");
		this.addToMap("#A0785A", "Chamoisee");
		this.addToMap("#F7E7CE", "Champagne");
		this.addToMap("#36454F", "Charcoal");
		this.addToMap("#232B2B", "Charleston green");
		this.addToMap("#E68FAC", "Charm pink");
		this.addToMap("#DFFF00", "Chartreuse");
		this.addToMap("#7FFF00", "Chartreuse (web)");
		this.addToMap("#DE3163", "Cherry");
		this.addToMap("#FFB7C5", "Cherry blossom pink");
		this.addToMap("#954535", "Chestnut");
		this.addToMap("#A8516E", "China rose");
		this.addToMap("#AA381E", "Chinese red");
		this.addToMap("#856088", "Chinese violet");
		this.addToMap("#7B3F00", "Chocolate");
		this.addToMap("#FFA700", "Chrome yellow");
		this.addToMap("#98817B", "Cinereous");
		this.addToMap("#E4D00A", "Citrine");
		this.addToMap("#9FA91F", "Citron");
		this.addToMap("#7F1734", "Claret");
		this.addToMap("#FBCCE7", "Classic rose");
		this.addToMap("#0047AB", "Cobalt");
		this.addToMap("#D2691E", "Cocoa brown");
		this.addToMap("#965A3E", "Coconut");
		this.addToMap("#6F4E37", "Coffee Brown");
		this.addToMap("#9BDDFF", "Columbia blue");
		this.addToMap("#002E63", "Cool black");
		this.addToMap("#8C92AC", "Cool grey");
		this.addToMap("#B87333", "Copper");
		this.addToMap("#AD6F69", "Copper penny");
		this.addToMap("#CB6D51", "Copper red");
		this.addToMap("#996666", "Copper rose");
		this.addToMap("#FF3800", "Coquelicot");
		this.addToMap("#FF7F50", "Coral");
		this.addToMap("#F88379", "Coral pink");
		this.addToMap("#FF4040", "Coral red");
		this.addToMap("#893F45", "Cordovan");
		this.addToMap("#FBEC5D", "Corn Yellow");
		this.addToMap("#B31B1B", "Cornell Red");
		this.addToMap("#6495ED", "Cornflower blue");
		this.addToMap("#FFF8DC", "Cornsilk");
		this.addToMap("#FFF8E7", "Cosmic latte");
		this.addToMap("#FFBCD9", "Cotton candy");
		this.addToMap("#FFFDD0", "Cream");
		this.addToMap("#DC143C", "Crimson");
		this.addToMap("#BE0032", "Crimson glory");
		this.addToMap("#00B7EB", "Cyan");
		this.addToMap("#58427C", "Cyber grape");
		this.addToMap("#FFD300", "Cyber yellow");
		this.addToMap("#FFFF31", "Daffodil");
		this.addToMap("#F0E130", "Dandelion");
		this.addToMap("#00008B", "Dark blue");
		this.addToMap("#666699", "Dark blue-gray");
		this.addToMap("#654321", "Dark brown");
		this.addToMap("#5D3954", "Dark byzantium");
		this.addToMap("#A40000", "Dark candy apple red");
		this.addToMap("#08457E", "Dark cerulean");
		this.addToMap("#986960", "Dark chestnut");
		this.addToMap("#CD5B45", "Dark coral");
		this.addToMap("#008B8B", "Dark cyan");
		this.addToMap("#536878", "Dark electric blue");
		this.addToMap("#B8860B", "Dark goldenrod");
		this.addToMap("#A9A9A9", "Dark gray");
		this.addToMap("#013220", "Dark green");
		this.addToMap("#00416A", "Dark imperial blue");
		this.addToMap("#1A2421", "Dark jungle green");
		this.addToMap("#BDB76B", "Dark khaki");
		this.addToMap("#734F96", "Dark lavender");
		this.addToMap("#534B4F", "Dark liver");
		this.addToMap("#543D37", "Dark liver (horses)");
		this.addToMap("#8B008B", "Dark magenta");
		this.addToMap("#003366", "Dark midnight blue");
		this.addToMap("#4A5D23", "Dark moss green");
		this.addToMap("#556B2F", "Dark olive green");
		this.addToMap("#FF8C00", "Dark orange");
		this.addToMap("#9932CC", "Dark orchid");
		this.addToMap("#779ECB", "Dark pastel blue");
		this.addToMap("#03C03C", "Dark pastel green");
		this.addToMap("#966FD6", "Dark pastel purple");
		this.addToMap("#C23B22", "Dark pastel red");
		this.addToMap("#E75480", "Dark pink");
		this.addToMap("#003399", "Dark powder blue");
		this.addToMap("#4F3A3C", "Dark puce");
		this.addToMap("#872657", "Dark raspberry");
		this.addToMap("#8B0000", "Dark red");
		this.addToMap("#E9967A", "Dark salmon");
		this.addToMap("#560319", "Dark scarlet");
		this.addToMap("#8FBC8F", "Dark sea green");
		this.addToMap("#3C1414", "Dark sienna");
		this.addToMap("#8CBED6", "Dark sky blue");
		this.addToMap("#483D8B", "Dark slate blue");
		this.addToMap("#2F4F4F", "Dark slate gray");
		this.addToMap("#177245", "Dark spring green");
		this.addToMap("#918151", "Dark tan");
		this.addToMap("#FFA812", "Dark tangerine");
		this.addToMap("#CC4E5C", "Dark terra cotta");
		this.addToMap("#00CED1", "Dark turquoise");
		this.addToMap("#D1BEA8", "Dark vanilla");
		this.addToMap("#9400D3", "Dark violet");
		this.addToMap("#9B870C", "Dark yellow");
		this.addToMap("#00703C", "Dartmouth green");
		this.addToMap("#555555", "Davy's grey");
		this.addToMap("#D70A53", "Debian red");
		this.addToMap("#A9203E", "Deep carmine");
		this.addToMap("#EF3038", "Deep carmine pink");
		this.addToMap("#E9692C", "Deep carrot orange");
		this.addToMap("#DA3287", "Deep cerise");
		this.addToMap("#B94E48", "Deep chestnut");
		this.addToMap("#C154C1", "Deep fuchsia");
		this.addToMap("#004B49", "Deep jungle green");
		this.addToMap("#F5C71A", "Deep lemon");
		this.addToMap("#9955BB", "Deep lilac");
		this.addToMap("#CC00CC", "Deep magenta");
		this.addToMap("#D473D4", "Deep mauve");
		this.addToMap("#355E3B", "Deep moss green");
		this.addToMap("#FFCBA4", "Deep peach");
		this.addToMap("#A95C68", "Deep puce");
		this.addToMap("#843F5B", "Deep ruby");
		this.addToMap("#FF9933", "Deep saffron");
		this.addToMap("#00BFFF", "Deep sky blue");
		this.addToMap("#4A646C", "Deep Space Sparkle");
		this.addToMap("#7E5E60", "Deep Taupe");
		this.addToMap("#66424D", "Deep Tuscan red");
		this.addToMap("#BA8759", "Deer");
		this.addToMap("#1560BD", "Denim");
		this.addToMap("#EDC9AF", "Desert sand");
		this.addToMap("#EA3C53", "Desire");
		this.addToMap("#B9F2FF", "Diamond");
		this.addToMap("#696969", "Dim gray");
		this.addToMap("#9B7653", "Dirt");
		this.addToMap("#1E90FF", "Dodger blue");
		this.addToMap("#D71868", "Dogwood rose");
		this.addToMap("#85BB65", "Dollar bill");
		this.addToMap("#664C28", "Donkey Brown");
		this.addToMap("#00009C", "Duke blue");
		this.addToMap("#E5CCC9", "Dust storm");
		this.addToMap("#EFDFBB", "Dutch white");
		this.addToMap("#E1A95F", "Earth yellow");
		this.addToMap("#555D50", "Ebony");
		this.addToMap("#1B1B1B", "Eerie black");
		this.addToMap("#614051", "Eggplant");
		this.addToMap("#F0EAD6", "Eggshell");
		this.addToMap("#1034A6", "Egyptian blue");
		this.addToMap("#7DF9FF", "Electric blue");
		this.addToMap("#FF003F", "Electric crimson");
		this.addToMap("#00FF00", "Electric green");
		this.addToMap("#6F00FF", "Electric indigo");
		this.addToMap("#CCFF00", "Electric lime");
		this.addToMap("#BF00FF", "Electric purple");
		this.addToMap("#3F00FF", "Electric ultramarine");
		this.addToMap("#FFFF00", "Electric yellow");
		this.addToMap("#50C878", "Emerald");
		this.addToMap("#6C3082", "Eminence");
		this.addToMap("#1B4D3E", "English green");
		this.addToMap("#B48395", "English lavender");
		this.addToMap("#AB4B52", "English red");
		this.addToMap("#563C5C", "English violet");
		this.addToMap("#96C8A2", "Eton blue");
		this.addToMap("#44D7A8", "Eucalyptus");
		this.addToMap("#801818", "Falu red");
		this.addToMap("#B53389", "Fandango");
		this.addToMap("#DE5285", "Fandango pink");
		this.addToMap("#F400A1", "Fashion fuchsia");
		this.addToMap("#E5AA70", "Fawn");
		this.addToMap("#4D5D53", "Feldgrau");
		this.addToMap("#4F7942", "Fern green");
		this.addToMap("#FF2800", "Ferrari Red");
		this.addToMap("#6C541E", "Field drab");
		this.addToMap("#B22222", "Firebrick");
		this.addToMap("#CE2029", "Fire engine red");
		this.addToMap("#E25822", "Flame");
		this.addToMap("#FC8EAC", "Flamingo pink");
		this.addToMap("#F7E98E", "Flavescent");
		this.addToMap("#EEDC82", "Flax");
		this.addToMap("#A2006D", "Flirt");
		this.addToMap("#FFFAF0", "Floral white");
		this.addToMap("#FFBF00", "Fluorescent orange");
		this.addToMap("#FF1493", "Fluorescent pink");
		this.addToMap("#FF004F", "Folly");
		this.addToMap("#014421", "Forest green");
		this.addToMap("#228B22", "Forest green (web)");
		this.addToMap("#856D4D", "French bistre");
		this.addToMap("#0072BB", "French blue");
		this.addToMap("#FD3F92", "French fuchsia");
		this.addToMap("#86608E", "French lilac");
		this.addToMap("#9EFD38", "French lime");
		this.addToMap("#FD6C9E", "French pink");
		this.addToMap("#4E1609", "French puce");
		this.addToMap("#C72C48", "French raspberry");
		this.addToMap("#F64A8A", "French rose");
		this.addToMap("#77B5FE", "French sky blue");
		this.addToMap("#8806CE", "French violet");
		this.addToMap("#AC1E44", "French wine");
		this.addToMap("#A6E7FF", "Fresh Air");
		this.addToMap("#FF77FF", "Fuchsia pink");
		this.addToMap("#CC397B", "Fuchsia purple");
		this.addToMap("#C74375", "Fuchsia rose");
		this.addToMap("#E48400", "Fulvous");
		this.addToMap("#CC6666", "Fuzzy Wuzzy");
		this.addToMap("#DCDCDC", "Gainsboro");
		this.addToMap("#E49B0F", "Gamboge");
		this.addToMap("#007F66", "Generic viridian");
		this.addToMap("#F8F8FF", "Ghost white");
		this.addToMap("#FE5A1D", "Giants orange");
		this.addToMap("#B06500", "Ginger");
		this.addToMap("#6082B6", "Glaucous");
		this.addToMap("#E6E8FA", "Glitter");
		this.addToMap("#00AB66", "GO green");
		this.addToMap("#D4AF37", "Gold (metallic)");
		this.addToMap("#FFD700", "Gold (web) (Golden)");
		this.addToMap("#85754E", "Gold Fusion");
		this.addToMap("#996515", "Golden brown");
		this.addToMap("#FCC200", "Golden poppy");
		this.addToMap("#FFDF00", "Golden yellow");
		this.addToMap("#DAA520", "Goldenrod");
		this.addToMap("#A8E4A0", "Granny Smith Apple");
		this.addToMap("#6F2DA8", "Grape");
		this.addToMap("#808080", "Gray");
		this.addToMap("#BEBEBE", "Gray (X11 gray)");
		this.addToMap("#465945", "Gray-asparagus");
		this.addToMap("#1CAC78", "Green (Crayola)");
		this.addToMap("#008000", "Green");
		this.addToMap("#00A877", "Green (Munsell)");
		this.addToMap("#009F6B", "Green (NCS)");
		this.addToMap("#00A550", "Green (pigment)");
		this.addToMap("#66B032", "Green (RYB)");
		this.addToMap("#ADFF2F", "Green-yellow");
		this.addToMap("#A99A86", "Grullo");
		this.addToMap("#663854", "Halaya ube");
		this.addToMap("#446CCF", "Han blue");
		this.addToMap("#5218FA", "Han purple");
		this.addToMap("#E9D66B", "Hansa yellow");
		this.addToMap("#3FFF00", "Harlequin");
		this.addToMap("#C90016", "Harvard crimson");
		this.addToMap("#DA9100", "Harvest gold");
		this.addToMap("#DF73FF", "Heliotrope");
		this.addToMap("#AA98A9", "Heliotrope gray");
		this.addToMap("#F0FFF0", "Honeydew");
		this.addToMap("#006DB0", "Honolulu blue");
		this.addToMap("#49796B", "Hooker's green");
		this.addToMap("#FF1DCE", "Hot magenta");
		this.addToMap("#FF69B4", "Hot pink");
		this.addToMap("#71A6D2", "Iceberg");
		this.addToMap("#FCF75E", "Icterine");
		this.addToMap("#319177", "Illuminating Emerald");
		this.addToMap("#602F6B", "Imperial");
		this.addToMap("#002395", "Imperial blue");
		this.addToMap("#66023C", "Imperial purple");
		this.addToMap("#ED2939", "Imperial red");
		this.addToMap("#B2EC5D", "Inchworm");
		this.addToMap("#4C516D", "Independence");
		this.addToMap("#138808", "India green");
		this.addToMap("#CD5C5C", "Indian red");
		this.addToMap("#E3A857", "Indian yellow");
		this.addToMap("#4B0082", "Indigo");
		this.addToMap("#002FA7", "International Klein Blue");
		this.addToMap("#FF4F00", "International orange (aerospace)");
		this.addToMap("#BA160C", "International orange (engineering)");
		this.addToMap("#C0362C", "International orange (Golden Gate Bridge)");
		this.addToMap("#5A4FCF", "Iris");
		this.addToMap("#F4F0EC", "Isabelline");
		this.addToMap("#009000", "Islamic green");
		this.addToMap("#B2FFFF", "Italian sky blue");
		this.addToMap("#FFFFF0", "Ivory");
		this.addToMap("#00A86B", "Jade");
		this.addToMap("#9D2933", "Japanese carmine");
		this.addToMap("#264348", "Japanese indigo");
		this.addToMap("#5B3256", "Japanese violet");
		this.addToMap("#D73B3E", "Jasper");
		this.addToMap("#A50B5E", "Jazzberry jam");
		this.addToMap("#DA614E", "Jelly Bean");
		this.addToMap("#343434", "Jet");
		this.addToMap("#F4CA16", "Jonquil");
		this.addToMap("#8AB9F1", "Jordy blue");
		this.addToMap("#BDDA57", "June bud");
		this.addToMap("#29AB87", "Jungle green");
		this.addToMap("#4CBB17", "Kelly green");
		this.addToMap("#7C1C05", "Kenyan copper");
		this.addToMap("#3AB09E", "Keppel");
		this.addToMap("#C3B091", "Khaki");
		this.addToMap("#E79FC4", "Kobi");
		this.addToMap("#354230", "Kombu green");
		this.addToMap("#E8000D", "KU Crimson");
		this.addToMap("#087830", "La Salle Green");
		this.addToMap("#D6CADD", "Languid lavender");
		this.addToMap("#26619C", "Lapis lazuli");
		this.addToMap("#A9BA9D", "Laurel green");
		this.addToMap("#CF1020", "Lava");
		this.addToMap("#B57EDC", "Lavender (floral)");
		this.addToMap("#CCCCFF", "Lavender blue");
		this.addToMap("#FFF0F5", "Lavender blush");
		this.addToMap("#C4C3D0", "Lavender gray");
		this.addToMap("#9457EB", "Lavender indigo");
		this.addToMap("#EE82EE", "Lavender magenta");
		this.addToMap("#E6E6FA", "Lavender mist");
		this.addToMap("#FBAED2", "Lavender pink");
		this.addToMap("#967BB6", "Lavender purple");
		this.addToMap("#FBA0E3", "Lavender rose");
		this.addToMap("#7CFC00", "Lawn green");
		this.addToMap("#FFF700", "Lemon");
		this.addToMap("#FFFACD", "Lemon chiffon");
		this.addToMap("#CCA01D", "Lemon curry");
		this.addToMap("#FDFF00", "Lemon glacier");
		this.addToMap("#E3FF00", "Lemon lime");
		this.addToMap("#F6EABE", "Lemon meringue");
		this.addToMap("#FFF44F", "Lemon yellow");
		this.addToMap("#1A1110", "Licorice");
		this.addToMap("#545AA7", "Liberty");
		this.addToMap("#FDD5B1", "Light apricot");
		this.addToMap("#ADD8E6", "Light blue");
		this.addToMap("#B5651D", "Light brown");
		this.addToMap("#E66771", "Light carmine pink");
		this.addToMap("#F08080", "Light coral");
		this.addToMap("#93CCEA", "Light cornflower blue");
		this.addToMap("#F56991", "Light crimson");
		this.addToMap("#E0FFFF", "Light cyan");
		this.addToMap("#FF5CCD", "Light deep pink");
		this.addToMap("#C8AD7F", "Light French beige");
		this.addToMap("#F984EF", "Light fuchsia pink");
		this.addToMap("#FAFAD2", "Light goldenrod yellow");
		this.addToMap("#D3D3D3", "Light gray");
		this.addToMap("#90EE90", "Light green");
		this.addToMap("#FFB3DE", "Light hot pink");
		this.addToMap("#F0E68C", "Light khaki");
		this.addToMap("#D39BCB", "Light medium orchid");
		this.addToMap("#ADDFAD", "Light moss green");
		this.addToMap("#E6A8D7", "Light orchid");
		this.addToMap("#B19CD9", "Light pastel purple");
		this.addToMap("#FFB6C1", "Light pink");
		this.addToMap("#E97451", "Light red ochre");
		this.addToMap("#FFA07A", "Light salmon");
		this.addToMap("#FF9999", "Light salmon pink");
		this.addToMap("#20B2AA", "Light sea green");
		this.addToMap("#87CEFA", "Light sky blue");
		this.addToMap("#778899", "Light slate gray");
		this.addToMap("#B0C4DE", "Light steel blue");
		this.addToMap("#B38B6D", "Light taupe");
		this.addToMap("#FFFFE0", "Light yellow");
		this.addToMap("#C8A2C8", "Lilac");
		this.addToMap("#BFFF00", "Lime");
		this.addToMap("#32CD32", "Lime green");
		this.addToMap("#9DC209", "Limerick");
		this.addToMap("#195905", "Lincoln green");
		this.addToMap("#FAF0E6", "Linen");
		this.addToMap("#6CA0DC", "Little boy blue");
		this.addToMap("#B86D29", "Liver (dogs)");
		this.addToMap("#6C2E1F", "Liver");
		this.addToMap("#987456", "Liver chestnut");
		this.addToMap("#FFE4CD", "Lumber");
		this.addToMap("#E62020", "Lust");
		this.addToMap("#FF00FF", "Magenta");
		this.addToMap("#CA1F7B", "Magenta (dye)");
		this.addToMap("#D0417E", "Magenta (Pantone)");
		this.addToMap("#FF0090", "Magenta (process)");
		this.addToMap("#9F4576", "Magenta haze");
		this.addToMap("#AAF0D1", "Magic mint");
		this.addToMap("#F8F4FF", "Magnolia");
		this.addToMap("#C04000", "Mahogany");
		this.addToMap("#6050DC", "Majorelle Blue");
		this.addToMap("#0BDA51", "Malachite");
		this.addToMap("#979AAA", "Manatee");
		this.addToMap("#FF8243", "Mango Tango");
		this.addToMap("#74C365", "Mantis");
		this.addToMap("#880085", "Mardi Gras");
		this.addToMap("#800000", "Maroon");
		this.addToMap("#E0B0FF", "Mauve");
		this.addToMap("#915F6D", "Mauve taupe");
		this.addToMap("#EF98AA", "Mauvelous");
		this.addToMap("#4C9141", "May green");
		this.addToMap("#73C2FB", "Maya blue");
		this.addToMap("#E5B73B", "Meat brown");
		this.addToMap("#66DDAA", "Medium aquamarine");
		this.addToMap("#0000CD", "Medium blue");
		this.addToMap("#E2062C", "Medium candy apple red");
		this.addToMap("#AF4035", "Medium carmine");
		this.addToMap("#035096", "Medium electric blue");
		this.addToMap("#1C352D", "Medium jungle green");
		this.addToMap("#BA55D3", "Medium orchid");
		this.addToMap("#9370DB", "Medium purple");
		this.addToMap("#BB3385", "Medium red-violet");
		this.addToMap("#AA4069", "Medium ruby");
		this.addToMap("#3CB371", "Medium sea green");
		this.addToMap("#80DAEB", "Medium sky blue");
		this.addToMap("#7B68EE", "Medium slate blue");
		this.addToMap("#C9DC87", "Medium spring bud");
		this.addToMap("#00FA9A", "Medium spring green");
		this.addToMap("#674C47", "Medium taupe");
		this.addToMap("#48D1CC", "Medium turquoise");
		this.addToMap("#D9603B", "Pale vermilion");
		this.addToMap("#F8B878", "Mellow apricot");
		this.addToMap("#F8DE7E", "Mellow yellow");
		this.addToMap("#FDBCB4", "Melon");
		this.addToMap("#0A7E8C", "Metallic Seaweed");
		this.addToMap("#9C7C38", "Metallic Sunburst");
		this.addToMap("#E4007C", "Mexican pink");
		this.addToMap("#191970", "Midnight blue");
		this.addToMap("#004953", "Midnight green (eagle green)");
		this.addToMap("#FFC40C", "Mikado yellow");
		this.addToMap("#E3F988", "Mindaro");
		this.addToMap("#3EB489", "Mint");
		this.addToMap("#F5FFFA", "Mint cream");
		this.addToMap("#98FF98", "Mint green");
		this.addToMap("#FFE4E1", "Misty rose");
		this.addToMap("#73A9C2", "Moonstone blue");
		this.addToMap("#AE0C00", "Mordant red 19");
		this.addToMap("#8A9A5B", "Moss green");
		this.addToMap("#30BA8F", "Mountain Meadow");
		this.addToMap("#997A8D", "Mountbatten pink");
		this.addToMap("#18453B", "MSU Green");
		this.addToMap("#306030", "Mughal green");
		this.addToMap("#C54B8C", "Mulberry");
		this.addToMap("#FFDB58", "Mustard");
		this.addToMap("#317873", "Myrtle green");
		this.addToMap("#F6ADC6", "Nadeshiko pink");
		this.addToMap("#2A8000", "Napier green");
		this.addToMap("#FFDEAD", "Navajo white");
		this.addToMap("#000080", "Navy");
		this.addToMap("#FFA343", "Neon Carrot");
		this.addToMap("#FE4164", "Neon fuchsia");
		this.addToMap("#39FF14", "Neon green");
		this.addToMap("#214FC6", "New Car");
		this.addToMap("#D7837F", "New York pink");
		this.addToMap("#A4DDED", "Non-photo blue");
		this.addToMap("#059033", "North Texas Green");
		this.addToMap("#E9FFDB", "Nyanza");
		this.addToMap("#0077BE", "Ocean Boat Blue");
		this.addToMap("#CC7722", "Ochre");
		this.addToMap("#43302E", "Old burgundy");
		this.addToMap("#CFB53B", "Old gold");
		this.addToMap("#FDF5E6", "Old lace");
		this.addToMap("#796878", "Old lavender");
		this.addToMap("#673147", "Old mauve");
		this.addToMap("#867E36", "Old moss green");
		this.addToMap("#C08081", "Old rose");
		this.addToMap("#808000", "Olive");
		this.addToMap("#6B8E23", "Olive Drab #3");
		this.addToMap("#3C341F", "Olive Drab #7");
		this.addToMap("#9AB973", "Olivine");
		this.addToMap("#353839", "Onyx");
		this.addToMap("#B784A7", "Opera mauve");
		this.addToMap("#FF7F00", "Orange");
		this.addToMap("#FF7538", "Orange (Crayola)");
		this.addToMap("#FF5800", "Orange (Pantone)");
		this.addToMap("#FB9902", "Orange (RYB)");
		this.addToMap("#FFA500", "Orange (web)");
		this.addToMap("#FF9F00", "Orange peel");
		this.addToMap("#FF4500", "Orange-red");
		this.addToMap("#DA70D6", "Orchid");
		this.addToMap("#F2BDCD", "Orchid pink");
		this.addToMap("#FB4F14", "Orioles orange");
		this.addToMap("#414A4C", "Outer Space");
		this.addToMap("#FF6E4A", "Outrageous Orange");
		this.addToMap("#002147", "Oxford Blue");
		this.addToMap("#990000", "Crimson Red");
		this.addToMap("#006600", "Pakistan green");
		this.addToMap("#273BE2", "Palatinate blue");
		this.addToMap("#682860", "Palatinate purple");
		this.addToMap("#BCD4E6", "Pale aqua");
		this.addToMap("#AFEEEE", "Pale blue");
		this.addToMap("#987654", "Pale brown");
		this.addToMap("#9BC4E2", "Pale cerulean");
		this.addToMap("#DDADAF", "Pale chestnut");
		this.addToMap("#DA8A67", "Pale copper");
		this.addToMap("#ABCDEF", "Pale cornflower blue");
		this.addToMap("#E6BE8A", "Pale gold");
		this.addToMap("#EEE8AA", "Pale goldenrod");
		this.addToMap("#98FB98", "Pale green");
		this.addToMap("#DCD0FF", "Pale lavender");
		this.addToMap("#F984E5", "Pale magenta");
		this.addToMap("#FADADD", "Pale pink");
		this.addToMap("#DDA0DD", "Pale plum");
		this.addToMap("#DB7093", "Pale red-violet");
		this.addToMap("#96DED1", "Pale robin egg blue");
		this.addToMap("#C9C0BB", "Pale silver");
		this.addToMap("#ECEBBD", "Pale spring bud");
		this.addToMap("#BC987E", "Pale taupe");
		this.addToMap("#78184A", "Pansy purple");
		this.addToMap("#009B7D", "Paolo Veronese green");
		this.addToMap("#FFEFD5", "Papaya whip");
		this.addToMap("#E63E62", "Paradise pink");
		this.addToMap("#AEC6CF", "Pastel blue");
		this.addToMap("#836953", "Pastel brown");
		this.addToMap("#CFCFC4", "Pastel gray");
		this.addToMap("#77DD77", "Pastel green");
		this.addToMap("#F49AC2", "Pastel magenta");
		this.addToMap("#FFB347", "Pastel orange");
		this.addToMap("#DEA5A4", "Pastel pink");
		this.addToMap("#B39EB5", "Pastel purple");
		this.addToMap("#FF6961", "Pastel red");
		this.addToMap("#CB99C9", "Pastel violet");
		this.addToMap("#FDFD96", "Pastel yellow");
		this.addToMap("#FFE5B4", "Peach");
		this.addToMap("#FFCC99", "Peach-orange");
		this.addToMap("#FFDAB9", "Peach puff");
		this.addToMap("#FADFAD", "Peach-yellow");
		this.addToMap("#D1E231", "Pear");
		this.addToMap("#EAE0C8", "Pearl");
		this.addToMap("#88D8C0", "Pearl Aqua");
		this.addToMap("#B768A2", "Pearly purple");
		this.addToMap("#E6E200", "Peridot");
		this.addToMap("#1C39BB", "Persian blue");
		this.addToMap("#00A693", "Persian green");
		this.addToMap("#32127A", "Persian indigo");
		this.addToMap("#D99058", "Persian orange");
		this.addToMap("#F77FBE", "Persian pink");
		this.addToMap("#701C1C", "Persian plum");
		this.addToMap("#CC3333", "Persian red");
		this.addToMap("#FE28A2", "Persian rose");
		this.addToMap("#EC5800", "Persimmon");
		this.addToMap("#CD853F", "Peru");
		this.addToMap("#000F89", "Phthalo blue");
		this.addToMap("#123524", "Phthalo green");
		this.addToMap("#45B1E8", "Picton blue");
		this.addToMap("#C30B4E", "Pictorial carmine");
		this.addToMap("#FDDDE6", "Piggy pink");
		this.addToMap("#01796F", "Pine green");
		this.addToMap("#FFC0CB", "Pink");
		this.addToMap("#D74894", "Pink (Pantone)");
		this.addToMap("#FFDDF4", "Pink lace");
		this.addToMap("#D8B2D1", "Pink lavender");
		this.addToMap("#FF9966", "Pink-orange");
		this.addToMap("#E7ACCF", "Pink pearl");
		this.addToMap("#F78FA7", "Pink Sherbet");
		this.addToMap("#93C572", "Pistachio");
		this.addToMap("#E5E4E2", "Platinum");
		this.addToMap("#8E4585", "Plum");
		this.addToMap("#BE4F62", "Popstar");
		this.addToMap("#FF5A36", "Portland Orange");
		this.addToMap("#B0E0E6", "Powder blue");
		this.addToMap("#FF8F00", "Princeton orange");
		this.addToMap("#003153", "Prussian blue");
		this.addToMap("#DF00FF", "Psychedelic purple");
		this.addToMap("#CC8899", "Puce");
		this.addToMap("#644117", "Pullman Brown (UPS Brown)");
		this.addToMap("#FF7518", "Pumpkin");
		this.addToMap("#800080", "Deep purple");
		this.addToMap("#9F00C5", "Purple (Munsell)");
		this.addToMap("#A020F0", "Purple");
		this.addToMap("#69359C", "Purple Heart");
		this.addToMap("#9678B6", "Purple mountain majesty");
		this.addToMap("#4E5180", "Purple navy");
		this.addToMap("#FE4EDA", "Purple pizzazz");
		this.addToMap("#50404D", "Purple taupe");
		this.addToMap("#9A4EAE", "Purpureus");
		this.addToMap("#51484F", "Quartz");
		this.addToMap("#436B95", "Queen blue");
		this.addToMap("#E8CCD7", "Queen pink");
		this.addToMap("#8E3A59", "Quinacridone magenta");
		this.addToMap("#FF355E", "Radical Red");
		this.addToMap("#FBAB60", "Rajah");
		this.addToMap("#E30B5D", "Raspberry");
		this.addToMap("#E25098", "Raspberry pink");
		this.addToMap("#B3446C", "Raspberry rose");
		this.addToMap("#826644", "Raw umber");
		this.addToMap("#FF33CC", "Razzle dazzle rose");
		this.addToMap("#E3256B", "Razzmatazz");
		this.addToMap("#8D4E85", "Razzmic Berry");
		this.addToMap("#FF0000", "Red");
		this.addToMap("#EE204D", "Red (Crayola)");
		this.addToMap("#F2003C", "Red (Munsell)");
		this.addToMap("#C40233", "Red (NCS)");
		this.addToMap("#ED1C24", "Red (pigment)");
		this.addToMap("#FE2712", "Red (RYB)");
		this.addToMap("#A52A2A", "Red-brown");
		this.addToMap("#860111", "Red devil");
		this.addToMap("#FF5349", "Red-orange");
		this.addToMap("#E40078", "Red-purple");
		this.addToMap("#C71585", "Red-violet");
		this.addToMap("#A45A52", "Redwood");
		this.addToMap("#522D80", "Regalia");
		this.addToMap("#002387", "Resolution blue");
		this.addToMap("#777696", "Rhythm");
		this.addToMap("#004040", "Rich black");
		this.addToMap("#F1A7FE", "Rich brilliant lavender");
		this.addToMap("#D70040", "Rich carmine");
		this.addToMap("#0892D0", "Rich electric blue");
		this.addToMap("#A76BCF", "Rich lavender");
		this.addToMap("#B666D2", "Rich lilac");
		this.addToMap("#B03060", "Rich maroon");
		this.addToMap("#444C38", "Rifle green");
		this.addToMap("#704241", "Deep Roast coffee");
		this.addToMap("#00CCCC", "Robin egg blue");
		this.addToMap("#8A7F80", "Rocket metallic");
		this.addToMap("#838996", "Roman silver");
		this.addToMap("#F9429E", "Rose bonbon");
		this.addToMap("#674846", "Rose ebony");
		this.addToMap("#B76E79", "Rose gold");
		this.addToMap("#FF66CC", "Rose pink");
		this.addToMap("#C21E56", "Rose red");
		this.addToMap("#905D5D", "Rose taupe");
		this.addToMap("#AB4E52", "Rose vale");
		this.addToMap("#65000B", "Rosewood");
		this.addToMap("#D40000", "Rosso corsa");
		this.addToMap("#BC8F8F", "Rosy brown");
		this.addToMap("#0038A8", "Royal azure");
		this.addToMap("#002366", "Royal blue");
		this.addToMap("#4169E1", "Royal light blue");
		this.addToMap("#CA2C92", "Royal fuchsia");
		this.addToMap("#7851A9", "Royal purple");
		this.addToMap("#FADA5E", "Royal yellow");
		this.addToMap("#CE4676", "Ruber");
		this.addToMap("#D10056", "Rubine red");
		this.addToMap("#E0115F", "Ruby");
		this.addToMap("#9B111E", "Ruby red");
		this.addToMap("#FF0028", "Ruddy");
		this.addToMap("#BB6528", "Ruddy brown");
		this.addToMap("#E18E96", "Ruddy pink");
		this.addToMap("#A81C07", "Rufous");
		this.addToMap("#80461B", "Russet");
		this.addToMap("#679267", "Russian green");
		this.addToMap("#32174D", "Russian violet");
		this.addToMap("#B7410E", "Rust");
		this.addToMap("#DA2C43", "Rusty red");
		this.addToMap("#8B4513", "Saddle brown");
		this.addToMap("#FF6700", "Safety orange (blaze orange)");
		this.addToMap("#EED202", "Safety yellow");
		this.addToMap("#F4C430", "Saffron");
		this.addToMap("#BCB88A", "Sage");
		this.addToMap("#23297A", "St. Patrick's blue");
		this.addToMap("#FA8072", "Salmon");
		this.addToMap("#FF91A4", "Salmon pink");
		this.addToMap("#C2B280", "Sand");
		this.addToMap("#ECD540", "Sandstorm");
		this.addToMap("#F4A460", "Sandy brown");
		this.addToMap("#92000A", "Sangria");
		this.addToMap("#507D2A", "Sap green");
		this.addToMap("#0F52BA", "Sapphire");
		this.addToMap("#0067A5", "Sapphire blue");
		this.addToMap("#CBA135", "Satin sheen gold");
		this.addToMap("#FF2400", "Scarlet");
		this.addToMap("#FFD800", "School bus yellow");
		this.addToMap("#76FF7A", "Screamin' Green");
		this.addToMap("#006994", "Sea blue");
		this.addToMap("#2E8B57", "Sea green");
		this.addToMap("#321414", "Seal brown");
		this.addToMap("#FFF5EE", "Seashell");
		this.addToMap("#FFBA00", "Selective yellow");
		this.addToMap("#704214", "Sepia");
		this.addToMap("#8A795D", "Shadow");
		this.addToMap("#778BA5", "Shadow blue");
		this.addToMap("#FFCFF1", "Shampoo");
		this.addToMap("#009E60", "Shamrock green");
		this.addToMap("#8FD400", "Sheen Green");
		this.addToMap("#D98695", "Shimmering Blush");
		this.addToMap("#FC0FC0", "Shocking pink");
		this.addToMap("#882D17", "Sienna");
		this.addToMap("#C0C0C0", "Silver");
		this.addToMap("#ACACAC", "Silver chalice");
		this.addToMap("#5D89BA", "Silver Lake blue");
		this.addToMap("#C4AEAD", "Silver pink");
		this.addToMap("#BFC1C2", "Silver sand");
		this.addToMap("#CB410B", "Sinopia");
		this.addToMap("#007474", "Skobeloff");
		this.addToMap("#87CEEB", "Sky blue");
		this.addToMap("#CF71AF", "Sky magenta");
		this.addToMap("#6A5ACD", "Slate blue");
		this.addToMap("#708090", "Slate gray");
		this.addToMap("#C84186", "Smitten");
		this.addToMap("#738276", "Smoke");
		this.addToMap("#933D41", "Smokey topaz");
		this.addToMap("#100C08", "Smoky black");
		this.addToMap("#FFFAFA", "Snow");
		this.addToMap("#CEC8EF", "Soap");
		this.addToMap("#893843", "Solid pink");
		this.addToMap("#757575", "Sonic silver");
		this.addToMap("#9E1316", "Spartan Crimson");
		this.addToMap("#1D2951", "Space cadet");
		this.addToMap("#807532", "Spanish bistre");
		this.addToMap("#0070B8", "Spanish blue");
		this.addToMap("#D10047", "Spanish carmine");
		this.addToMap("#E51A4C", "Spanish crimson");
		this.addToMap("#989898", "Spanish gray");
		this.addToMap("#009150", "Spanish green");
		this.addToMap("#E86100", "Spanish orange");
		this.addToMap("#F7BFBE", "Spanish pink");
		this.addToMap("#E60026", "Spanish red");
		this.addToMap("#4C2882", "Spanish violet");
		this.addToMap("#007F5C", "Spanish viridian");
		this.addToMap("#0FC0FC", "Spiro Disco Ball");
		this.addToMap("#A7FC00", "Spring bud");
		this.addToMap("#00FF7F", "Spring green");
		this.addToMap("#007BB8", "Star command blue");
		this.addToMap("#4682B4", "Steel blue");
		this.addToMap("#CC33CC", "Steel pink");
		this.addToMap("#4F666A", "Stormcloud");
		this.addToMap("#E4D96F", "Straw");
		this.addToMap("#FC5A8D", "Strawberry");
		this.addToMap("#FFCC33", "Sunglow");
		this.addToMap("#E3AB57", "Sunray");
		this.addToMap("#FAD6A5", "Sunset");
		this.addToMap("#FD5E53", "Sunset orange");
		this.addToMap("#CF6BA9", "Super pink");
		this.addToMap("#D2B48C", "Tan");
		this.addToMap("#F94D00", "Tangelo");
		this.addToMap("#F28500", "Tangerine");
		this.addToMap("#FFCC00", "Tangerine yellow");
		this.addToMap("#483C32", "Dark Grayish Brown");
		this.addToMap("#8B8589", "Taupe gray");
		this.addToMap("#D0F0C0", "Tea green");
		this.addToMap("#F4C2C2", "Tea rose");
		this.addToMap("#008080", "Teal");
		this.addToMap("#367588", "Teal blue");
		this.addToMap("#99E6B3", "Teal deer");
		this.addToMap("#00827F", "Teal green");
		this.addToMap("#CF3476", "Telemagenta");
		this.addToMap("#CD5700", "Tenne");
		this.addToMap("#E2725B", "Terra cotta");
		this.addToMap("#D8BFD8", "Thistle");
		this.addToMap("#DE6FA1", "Thulian pink");
		this.addToMap("#FC89AC", "Tickle Me Pink");
		this.addToMap("#0ABAB5", "Tiffany Blue");
		this.addToMap("#E08D3C", "Tiger's eye");
		this.addToMap("#DBD7D2", "Timberwolf");
		this.addToMap("#EEE600", "Titanium yellow");
		this.addToMap("#FF6347", "Tomato");
		this.addToMap("#746CC0", "Toolbox");
		this.addToMap("#42B72A", "Toothpaste advert green");
		this.addToMap("#FFC87C", "Topaz");
		this.addToMap("#FD0E35", "Tractor red");
		this.addToMap("#00755E", "Tropical rain forest");
		this.addToMap("#0073CF", "True Blue");
		this.addToMap("#417DC1", "Tufts Blue");
		this.addToMap("#FF878D", "Tulip");
		this.addToMap("#DEAA88", "Tumbleweed");
		this.addToMap("#B57281", "Turkish rose");
		this.addToMap("#40E0D0", "Turquoise");
		this.addToMap("#00FFEF", "Turquoise blue");
		this.addToMap("#A0D6B4", "Turquoise green");
		this.addToMap("#7C4848", "Tuscan red");
		this.addToMap("#C09999", "Tuscany");
		this.addToMap("#8A496B", "Twilight lavender");
		this.addToMap("#0033AA", "UA blue");
		this.addToMap("#D9004C", "UA red");
		this.addToMap("#8878C3", "Ube");
		this.addToMap("#536895", "UCLA Blue");
		this.addToMap("#FFB300", "UCLA Gold");
		this.addToMap("#3CD070", "UFO Green");
		this.addToMap("#120A8F", "Ultramarine");
		this.addToMap("#4166F5", "Ultramarine blue");
		this.addToMap("#FF6FFF", "Ultra pink");
		this.addToMap("#635147", "Umber");
		this.addToMap("#FFDDCA", "Unbleached silk");
		this.addToMap("#5B92E5", "United Nations blue");
		this.addToMap("#B78727", "University of California Gold");
		this.addToMap("#FFFF66", "Unmellow yellow");
		this.addToMap("#7B1113", "UP Maroon");
		this.addToMap("#AE2029", "Upsdell red");
		this.addToMap("#E1AD21", "Urobilin");
		this.addToMap("#004F98", "USAFA blue");
		this.addToMap("#F77F00", "University of Tennessee Orange");
		this.addToMap("#D3003F", "Utah Crimson");
		this.addToMap("#F3E5AB", "Vanilla");
		this.addToMap("#F38FA9", "Vanilla ice");
		this.addToMap("#C5B358", "Vegas gold");
		this.addToMap("#C80815", "Venetian red");
		this.addToMap("#43B3AE", "Verdigris");
		this.addToMap("#E34234", "Medium vermilion");
		this.addToMap("#D9381E", "Vermilion");
		this.addToMap("#8F00FF", "Violet");
		this.addToMap("#7F00FF", "Violet (color wheel)");
		this.addToMap("#8601AF", "Violet (RYB)");
		this.addToMap("#324AB2", "Violet-blue");
		this.addToMap("#F75394", "Violet-red");
		this.addToMap("#40826D", "Viridian");
		this.addToMap("#009698", "Viridian green");
		this.addToMap("#922724", "Vivid auburn");
		this.addToMap("#9F1D35", "Vivid burgundy");
		this.addToMap("#DA1D81", "Vivid cerise");
		this.addToMap("#CC00FF", "Vivid orchid");
		this.addToMap("#00CCFF", "Vivid sky blue");
		this.addToMap("#FFA089", "Vivid tangerine");
		this.addToMap("#9F00FF", "Vivid violet");
		this.addToMap("#004242", "Warm black");
		this.addToMap("#A4F4F9", "Waterspout");
		this.addToMap("#645452", "Wenge");
		this.addToMap("#F5DEB3", "Wheat");
		this.addToMap("#FFFFFF", "White");
		this.addToMap("#F5F5F5", "White smoke");
		this.addToMap("#A2ADD0", "Wild blue yonder");
		this.addToMap("#D470A2", "Wild orchid");
		this.addToMap("#FF43A4", "Wild Strawberry");
		this.addToMap("#FC6C85", "Wild watermelon");
		this.addToMap("#FD5800", "Willpower orange");
		this.addToMap("#A75502", "Windsor tan");
		this.addToMap("#722F37", "Wine");
		this.addToMap("#C9A0DC", "Wisteria");
		this.addToMap("#C19A6B", "Wood brown");
		this.addToMap("#738678", "Xanadu");
		this.addToMap("#0F4D92", "Yale Blue");
		this.addToMap("#1C2841", "Yankees blue");
		this.addToMap("#FCE883", "Yellow (Crayola)");
		this.addToMap("#EFCC00", "Yellow (Munsell)");
		this.addToMap("#FEDF00", "Yellow (Pantone)");
		this.addToMap("#FEFE33", "Yellow");
		this.addToMap("#9ACD32", "Yellow Green");
		this.addToMap("#FFAE42", "Yellow Orange");
		this.addToMap("#FFF000", "Yellow rose");
		this.addToMap("#0014A8", "Zaffre");
		this.addToMap("#2C1608", "Zinnwaldite brown");
		this.addToMap("#39A78E", "Zomp");
	}
}

if(typeof module !== "undefined") {
	module.exports = Color;
} else {
	this.Color = Color;
}
